// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { tanstackRouter } from "@tanstack/router-plugin/vite";

// The route tree ships with the rest of the source and needs the same license
// header. TanStack Router rewrites the file whenever a route changes, so the
// header has to come from the generator rather than be added to the file.
const LICENSE_HEADER = [
  "// Copyright 2026 Google LLC",
  "//",
  '// Licensed under the Apache License, Version 2.0 (the "License");',
  "// you may not use this file except in compliance with the License.",
  "// You may obtain a copy of the License at",
  "//",
  "//     https://www.apache.org/licenses/LICENSE-2.0",
  "//",
  "// Unless required by applicable law or agreed to in writing, software",
  '// distributed under the License is distributed on an "AS IS" BASIS,',
  "// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.",
  "// See the License for the specific language governing permissions and",
  "// limitations under the License.",
].join("\n");

export default defineConfig({
  plugins: [
    tanstackRouter({
      target: "react",
      routesDirectory: "src/routes",
      generatedRouteTree: "src/routeTree.gen.ts",
      autoCodeSplitting: true,
      // Match the Biome formatter so the committed route tree passes format checks.
      quoteStyle: "double",
      semicolons: true,
      // Replaces the generator's default header, so include its three
      // suppression lines plus biome-ignore-all for adk-recipes CI.
      routeTreeFileHeader: [
        LICENSE_HEADER,
        "/* eslint-disable */",
        "// @ts-nocheck",
        "// noinspection JSUnusedGlobalSymbols",
        "// biome-ignore-all lint: generated by TanStack Router, which overwrites any edit.",
      ],
    }),
    react(),
  ],
  // Mirror the @/ → web/ alias from tsconfig so shared lib/components resolve.
  resolve: { alias: { "@": new URL(".", import.meta.url).pathname } },
  // Served by the FastAPI app at the root.
  base: "/",
  build: { outDir: "../static_v2", emptyOutDir: true },
  server: {
    // NOTE: /a2a must stream SSE unbuffered. Vite's dev proxy (http-proxy)
    // does not gzip responses, so Server-Sent Events pass through unbuffered.
    // Local edit to the vendored tree: /api added, and the default target moved
    // to the port tools/local_ui.sh serves on. Every dashboard read goes to
    // /api, so without it `npm run dev` renders the shell with empty panels.
    proxy: Object.fromEntries(
      ["/api", "/lha", "/a2a", "/feedback", "/.well-known"].map((p) => [
        p,
        {
          target: process.env.NEXT_PUBLIC_LHA_URL ?? "http://127.0.0.1:8080",
          changeOrigin: true,
          ws: true,
        },
      ]),
    ),
  },
});
