// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// biome-ignore-all lint: generated by TanStack Router, which overwrites any edit.

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ConfigRouteImport } from "./routes/config";
import { Route as CRouteImport } from "./routes/c";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as InvestigationsIndexRouteImport } from "./routes/investigations.index";
import { Route as InsightsIndexRouteImport } from "./routes/insights.index";
import { Route as InsightsInsightIdRouteImport } from "./routes/insights.$insightId";
import { Route as InvestigationsRunIdIndexRouteImport } from "./routes/investigations.$runId.index";
import { Route as InvestigationsRunIdCasesCaseIdRouteImport } from "./routes/investigations.$runId.cases.$caseId";

const ConfigRoute = ConfigRouteImport.update({
  id: "/config",
  path: "/config",
  getParentRoute: () => rootRouteImport,
} as any);
const CRoute = CRouteImport.update({
  id: "/c",
  path: "/c",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const InvestigationsIndexRoute = InvestigationsIndexRouteImport.update({
  id: "/investigations/",
  path: "/investigations/",
  getParentRoute: () => rootRouteImport,
} as any);
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: "/insights/",
  path: "/insights/",
  getParentRoute: () => rootRouteImport,
} as any);
const InsightsInsightIdRoute = InsightsInsightIdRouteImport.update({
  id: "/insights/$insightId",
  path: "/insights/$insightId",
  getParentRoute: () => rootRouteImport,
} as any);
const InvestigationsRunIdIndexRoute =
  InvestigationsRunIdIndexRouteImport.update({
    id: "/investigations/$runId/",
    path: "/investigations/$runId/",
    getParentRoute: () => rootRouteImport,
  } as any);
const InvestigationsRunIdCasesCaseIdRoute =
  InvestigationsRunIdCasesCaseIdRouteImport.update({
    id: "/investigations/$runId/cases/$caseId",
    path: "/investigations/$runId/cases/$caseId",
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/c": typeof CRoute;
  "/config": typeof ConfigRoute;
  "/insights/$insightId": typeof InsightsInsightIdRoute;
  "/insights/": typeof InsightsIndexRoute;
  "/investigations/": typeof InvestigationsIndexRoute;
  "/investigations/$runId/": typeof InvestigationsRunIdIndexRoute;
  "/investigations/$runId/cases/$caseId": typeof InvestigationsRunIdCasesCaseIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/c": typeof CRoute;
  "/config": typeof ConfigRoute;
  "/insights/$insightId": typeof InsightsInsightIdRoute;
  "/insights": typeof InsightsIndexRoute;
  "/investigations": typeof InvestigationsIndexRoute;
  "/investigations/$runId": typeof InvestigationsRunIdIndexRoute;
  "/investigations/$runId/cases/$caseId": typeof InvestigationsRunIdCasesCaseIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/c": typeof CRoute;
  "/config": typeof ConfigRoute;
  "/insights/$insightId": typeof InsightsInsightIdRoute;
  "/insights/": typeof InsightsIndexRoute;
  "/investigations/": typeof InvestigationsIndexRoute;
  "/investigations/$runId/": typeof InvestigationsRunIdIndexRoute;
  "/investigations/$runId/cases/$caseId": typeof InvestigationsRunIdCasesCaseIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/c"
    | "/config"
    | "/insights/$insightId"
    | "/insights/"
    | "/investigations/"
    | "/investigations/$runId/"
    | "/investigations/$runId/cases/$caseId";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/c"
    | "/config"
    | "/insights/$insightId"
    | "/insights"
    | "/investigations"
    | "/investigations/$runId"
    | "/investigations/$runId/cases/$caseId";
  id:
    | "__root__"
    | "/"
    | "/c"
    | "/config"
    | "/insights/$insightId"
    | "/insights/"
    | "/investigations/"
    | "/investigations/$runId/"
    | "/investigations/$runId/cases/$caseId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CRoute: typeof CRoute;
  ConfigRoute: typeof ConfigRoute;
  InsightsInsightIdRoute: typeof InsightsInsightIdRoute;
  InsightsIndexRoute: typeof InsightsIndexRoute;
  InvestigationsIndexRoute: typeof InvestigationsIndexRoute;
  InvestigationsRunIdIndexRoute: typeof InvestigationsRunIdIndexRoute;
  InvestigationsRunIdCasesCaseIdRoute: typeof InvestigationsRunIdCasesCaseIdRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/config": {
      id: "/config";
      path: "/config";
      fullPath: "/config";
      preLoaderRoute: typeof ConfigRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/c": {
      id: "/c";
      path: "/c";
      fullPath: "/c";
      preLoaderRoute: typeof CRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/investigations/": {
      id: "/investigations/";
      path: "/investigations";
      fullPath: "/investigations/";
      preLoaderRoute: typeof InvestigationsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/insights/": {
      id: "/insights/";
      path: "/insights";
      fullPath: "/insights/";
      preLoaderRoute: typeof InsightsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/insights/$insightId": {
      id: "/insights/$insightId";
      path: "/insights/$insightId";
      fullPath: "/insights/$insightId";
      preLoaderRoute: typeof InsightsInsightIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/investigations/$runId/": {
      id: "/investigations/$runId/";
      path: "/investigations/$runId";
      fullPath: "/investigations/$runId/";
      preLoaderRoute: typeof InvestigationsRunIdIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/investigations/$runId/cases/$caseId": {
      id: "/investigations/$runId/cases/$caseId";
      path: "/investigations/$runId/cases/$caseId";
      fullPath: "/investigations/$runId/cases/$caseId";
      preLoaderRoute: typeof InvestigationsRunIdCasesCaseIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CRoute: CRoute,
  ConfigRoute: ConfigRoute,
  InsightsInsightIdRoute: InsightsInsightIdRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  InvestigationsIndexRoute: InvestigationsIndexRoute,
  InvestigationsRunIdIndexRoute: InvestigationsRunIdIndexRoute,
  InvestigationsRunIdCasesCaseIdRoute: InvestigationsRunIdCasesCaseIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
